"""
Django settings for Hulks_GYM_System project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
"""
Ruta base del directorio del proyecto
"""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gdlwc-5t-*8nu6c^p#@b3l8saq&4d8&j11nkfabpgduxkh!d04"
"""
 Clave secreta utilizada para la firma criptográfica en Django
"""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
"""
Bandera de modo de depuración
"""
ALLOWED_HOSTS = []
"""
Lista de nombres de host que la instancia de Django puede servir
"""


# Application definition

INSTALLED_APPS = [
    """
    Lista de todas las aplicaciones Django activas en el proyecto
    """
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "Gestion_Inventario",
    'Inicio_Sesion',
    'Gestion_Membresia',
    'Gestion_Productos',
    'Gestion_Empleados',
    "Gestion_Clientes",
    "Gestion_Ventas"

]



#jazzmin settings
JAZZMIN_SETTINGS ={

    """
    Configuraciones específicas para el tema del administrador Jazzmin. Personaliza la apariencia del 
    panel de administración de Django
    """

    "theme": "darkly",
    "welcome_sign": "Inicio de Sesion",
    "site_title": "Hulk's Systems",
    "site_brand": "Hulk's GYM",
    "site_logo": "imagenes/Hulk.jpg",
    "login_logo": "imagenes/Hulk.jpg",

    "show_ui_builder": False,#  Poner True para editar wl disenio de la pagina
    "icons": { 
    "auth": "fas fa-users-cog",
    "auth.user": "fas fa-user",
    "auth.Group": "fas fa-users",
    "Gestion_Inventario.equipo": "fas fa-dumbbell",
    "Gestion_Membresia.membresia": "fas fa-address-card",
    "Gestion_Clientes.Miembro": "fas fa-user-friends",
    "Gestion_Ventas.Venta": "fas fa-store",
    "Gestion_Productos.Proveedor": "fas fa-truck",
    "Gestion_Productos.Categoria": "fas fa-tags",
    "Gestion_Productos.Producto": "fas fa-usd",
    "Gestion_Empleados.Empleado":"fas fa-briefcase",
    },
     "copyright": "Hulk's GYM",
     "custom_css": "css/custom_admin.css",
   
    
}

JAZZMIN_UI_TWEAKS = {
    """
    Configura ajustes de la interfaz de usuario de Jazzmin (detalles como tamaños de texto, 
    colores de la barra de navegación y estilos de la barra lateral)
    """

    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
}

MIDDLEWARE = [
    """
    Lista de clases middleware que procesan solicitudes y respuestas 
    """
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Hulks_GYM_System.urls"
"""
Ruta al módulo de URL principal del proyecto
"""


TEMPLATES = [
    {
        """
        Configuraciones para renderiza los archivos de plantilla HTML del pryecto
        """
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Hulks_GYM_System.wsgi.application"
"""
Ruta al objeto de aplicación WSGI del proyecto
"""

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    """
    Configuraciones para las bases de datos del proyecto
    """
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
"""
Validadores de contraseñas utilizados por el sistema de autenticación
"""

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-mx"
"""
Código de idioma para el proyecto
"""
TIME_ZONE = "America/Ciudad_Juarez"
"""
Zona horaria para el proyecto.
"""

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
"""
Url base para ubicar archivos estáticos (CSS, JavaScript, imágenes)
"""

STATICFILES_DIRS = [
    BASE_DIR / "static",
    """
    Rutas donde Django busca archivos estáticos
    """

]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
"""
Campo predeterminado para las claves primarias
"""

LOGIN_REDIRECT_URL = 'google.com' 
"""
Url a la que se redirige a los usuarios después de un inicio de sesión exitoso
"""
LOGOUT_REDIRECT_URL = 'login'
"""
Url a la que se redirige a los usuarios después de cerrar sesión
"""
